# Generated by Django 5.0.6 on 2024-05-14 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='categories',
            field=models.CharField(default='uncategorized', max_length=100),
        ),
    ]
